name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  env:
    SVC: ${{ vars.SVC }}
    PROJ: ${{ vars.PROJ }}
    AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  build_dev:
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_ECR_REPO: ${{ vars.AWS_ECR_REPO }}
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    container:
      image: docker:latest

    steps:
    - name: print env
      run: env
    - name: Check out
      uses: actions/checkout@main
    - name: Explore dir
      run: pwd; ls
    - name: install utilities
      run: apk add aws-cli
    - name: login to ECR
      run: aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_ECR_REPO
