name: Build and Deploy

on:
  push:
    branches: [ "main" ]

env:
  SVC: ${{ vars.SVC }}
  PROJ: ${{ vars.PROJ }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker:latest

    environment: staging
    env:
      AWS_ECR_REPO:            ${{ vars.AWS_ECR_REPO }}
      AWS_ACCESS_KEY_ID:       ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:   ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TAG:                     ${{ vars.SVC }}/${{ github.sha }}
      CLUSTER:                 ${{ vars.PROJ }}-${{ matrix.environment }}-cluster
      AWS_ECS_TASK_DEFINITION: ${{ vars.PROJ }}-${{ matrix.environment }}-${{ vars.SVC }}-task
      AWS_ECS_SERVICE:         ${{ vars.PROJ }}-${{ matrix.environment }}-${{ vars.SVC }}-service
      LATEST:                  ${{ vars.AWS_ECR_REPO }}/${{ vars.PROJ }}/${{ matrix.environment }}/${{ vars.SVC }}:latest
      IMAGE:                   ${{ vars.AWS_ECR_REPO }}/${{ vars.PROJ }}/${{ matrix.environment }}/${{ vars.SVC }}:${{ github.sha }}

    steps:
    - name: Check out
      uses: actions/checkout@main
    - name: short git commit SHA
      run: |
        sha=$(git rev-parse --short ${{ github.sha }})
        echo "SHA=$sha" >> $GITHUB_ENV
        echo "TAG=${{ vars.SVC }}/$sha" >> $GITHUB_ENV
        echo "IMAGE=${{ vars.AWS_ECR_REPO }}/${{ vars.PROJ }}/${{ matrix.environment }}/${{ vars.SVC }}:$sha" >> $GITHUB_ENV
    - name: print env
      run: env
    - name: Explore dir
      run: pwd; ls; uname -a
    - name: install utils
      run: apk add aws-cli jq
    - name: login to ECR
      run: aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_ECR_REPO
    - name: docker build
      run: docker build -t ${TAG} .
    - name: docker tag
      run: |
        docker tag ${TAG} ${IMAGE}
        docker tag ${TAG} ${LATEST}
    - name: docker push
      run: |
        docker push ${IMAGE}
        docker push ${LATEST}
        echo "Pushed images ${IMAGE} and ${LATEST}"
    - name: deploy
      run: |
        export revision=$(aws ecs describe-task-definition --task-definition $AWS_ECS_TASK_DEFINITION \
        | jq '.taskDefinition.containerDefinitions[0].image = env.IMAGE | .taskDefinition | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' \
        | xargs -0I{} aws ecs register-task-definition --cli-input-json {} | tee /dev/stderr | jq '.taskDefinition.revision')
        echo "Pushing revision $AWS_ECS_TASK_DEFINITION:$revision"
        aws ecs update-service --cluster $CLUSTER --service $AWS_ECS_SERVICE --task-definition $AWS_ECS_TASK_DEFINITION:${revision}
    - name: waiting for update to be completed
      run: |
        aws ecs wait services-stable --cluster $CLUSTER --service $AWS_ECS_SERVICE
        echo "Info - Deployment complete"
