name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SVC: ${{ vars.SVC }}
  PROJ: ${{ vars.PROJ }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker:latest
    strategy:
      matrix:
        environment: [dev, staging]

    environment: ${{ matrix.environment }}
    env:
      AWS_ECR_REPO:            ${{ vars.AWS_ECR_REPO }}
      AWS_ACCESS_KEY_ID:       ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:   ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TAG:                     ${{ vars.SVC }}/${{ github.sha }}
      CLUSTER:                 ${{ vars.PROJ }}-${{ matrix.environment }}-cluster
      AWS_ECS_TASK_DEFINITION: ${{ vars.PROJ }}-${{ matrix.environment }}-${{ vars.SVC }}-task
      AWS_ECS_SERVICE:         ${{ vars.PROJ }}-${{ matrix.environment }}-${{ vars.SVC }}-service
      LATEST:                  ${{ vars.AWS_ECR_REPO }}/${{ vars.PROJ }}/${{ matrix.environment }}/${{ vars.SVC }}:latest
      IMAGE:                   ${{ vars.AWS_ECR_REPO }}/${{ vars.PROJ }}/${{ matrix.environment }}/${{ vars.SVC }}:${{ github.sha }}

    steps:
    - name: Check out
      uses: actions/checkout@main
    - name: short git commit SHA
      run: echo "SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
    - name: print env
      run: env
    - name: Explore dir
      run: pwd; ls; uname -a
    - name: install utils
      run: apk add aws-cli jq
    - name: login to ECR
      run: aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_ECR_REPO
    - name: docker build
      run: |
        which docker
        docker build -t ${TAG} .
    - name: docker tag
      run: |
        docker tag ${TAG} ${IMAGE}
        docker tag ${TAG} ${LATEST}
    - name: docker push
      run: |
        docker push ${IMAGE}
        docker push ${LATEST}
        echo "Pushed images ${IMAGE} and ${LATEST}"
