name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy-template.yaml
    with:
      environment: dev
    secrets: inherit

  approve-staging:
    needs: deploy-dev
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: short git commit SHA
      run: echo "SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
    - name: manual approval
      uses: trstringer/manual-approval@v1
      timeout-minutes: 10
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: simolev
        minimum-approvals: 1
        issue-title: "Deploying to STAGING commit ${{ env.SHA }} (DEV -> STAGING)"
        issue-body: "Please approve or deny deploying version ${{ env.SHA }} to STAGING."
        exclude-workflow-initiator-as-approver: false
        additional-approved-words: 'ok'

  deploy-staging:
    needs: approve-staging
    uses: ./.github/workflows/deploy-template.yaml
    with:
      environment: staging
    secrets: inherit

  approve-prod:
    needs: deploy-staging
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Calculate short sha for the commit
      id: short-sha
      uses: benjlevesque/short-sha@v3.0
    - name: manual approval
      uses: trstringer/manual-approval@v1
      timeout-minutes: 10
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: simolev
        minimum-approvals: 1
        issue-title: "Deploying to PROD commit ${{ env.SHA }} (DEV -> STAGING -> PROD)"
        issue-body: "Please approve or deny deploying version ${{ env.SHA }} to PROD."
        exclude-workflow-initiator-as-approver: false
        additional-approved-words: 'ok'

  deploy-prod:
    needs: approve-prod
    uses: ./.github/workflows/deploy-template.yaml
    with:
      environment: prod
    secrets: inherit
