name: Build and deploy template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Target environment (dev, staging, prod)'

env:
  SVC: ${{ vars.SVC }}
  PROJ: ${{ vars.PROJ }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker:latest

    environment: ${{ inputs.environment }}
    env:
      AWS_ECR_REPO:            ${{ vars.AWS_ECR_REPO }}
      AWS_ACCESS_KEY_ID:       ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:   ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TAG:                     ${{ vars.SVC }}/${{ github.sha }}
      CLUSTER:                 ${{ vars.PROJ }}-${{ inputs.environment }}-cluster
      AWS_ECS_TASK_DEFINITION: ${{ vars.PROJ }}-${{ inputs.environment }}-${{ vars.SVC }}-task
      AWS_ECS_SERVICE:         ${{ vars.PROJ }}-${{ inputs.environment }}-${{ vars.SVC }}-service
      LATEST:                  ${{ vars.AWS_ECR_REPO }}/${{ vars.PROJ }}/${{ inputs.environment }}/${{ vars.SVC }}:latest
      IMAGE:                   ${{ vars.AWS_ECR_REPO }}/${{ vars.PROJ }}/${{ inputs.environment }}/${{ vars.SVC }}:${{ github.sha }}

    steps:
    - name: Check out
      uses: actions/checkout@main
    - name: short git commit SHA
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        sha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$sha" >> $GITHUB_ENV
        echo "TAG=${{ vars.SVC }}/$sha" >> $GITHUB_ENV
        echo "IMAGE=${{ vars.AWS_ECR_REPO }}/${{ vars.PROJ }}/${{ inputs.environment }}/${{ vars.SVC }}:$sha" >> $GITHUB_ENV
    - name: print env
      run: env
    - name: Explore dir
      run: pwd; ls; uname -a
    - name: install utils
      run: apk add aws-cli jq
